import pandas as pd 
import matplotlib.pyplot as plt 
df=pd.read_csv("netflix_titles.csv")
print(df.shape)
print(df.head())
print(df.isnull().sum())
df.dropna(inplace=True)
print(df.shape)
df["type"]=df["type"].dropna()
type_counts = df["type"].value_counts()
type_counts.plot(kind="bar",color=["red","purple"][:len(type_counts)])
plt.title("Movies vs TV shows")
plt.xlabel("Type")
plt.ylabel("Count")
plt.grid(axis="y")
plt.show() 
df["date_added"]=pd.to_datetime(df["date_added"],errors="coerce")
df["year_added"]=df["date_added"].dt.year
df["year_added"].value_counts().sort_index().plot(kind="line",color="green")
plt.title("Content over time")
plt.xlabel("Year")
plt.ylabel("No of Items Added")
plt.grid(True)
plt.show()
df["country"].value_counts().head(10).plot(kind="bar",color="orange")
plt.title("Top 10 Countries with Most Content")
plt.xlabel("Country")
plt.ylabel("No of Titles")
plt.show()
df["rating"].value_counts().plot(kind="pie",autopct="%1.1f%%")
plt.title("Rating Distribution")
plt.show()